version: '2'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /Users/jacknely/Apps/DocumentPortal:/DocumentPortal"
    links:
      - db:mysql
    container_name: document_web_1
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    container_name: document_db_1
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: document_db_1
